trigger:
  branches:
    include: ["master", "v?.*", "*_validate"]
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - template: azure-pipelines/build.yml
