trigger:
  branches:
    include: ["master", "v1.8", "*_validate"]
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool: Hosted VS2017
  steps:
  - template: azure-pipelines/build.yml
