steps:
- task: UseDotNet@2
  displayName: Install .NET Core SDK 3.0.100
  inputs:
    packageType: sdk
    version: 3.0.100
- script: dotnet --info
  displayName: Show dotnet SDK info

- script: dotnet publish src/MessagePack -c $(BuildConfiguration) -f netstandard2.0
  displayName: Build MessagePack

- script: src/MessagePack.UnityClient/build.sh -l $(Build.ArtifactStagingDirectory)/build_logs/unitypackage.log
  displayName: Build Unity package

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/build_logs
    ArtifactName: build_logs
    ArtifactType: Container
  displayName: Publish build_logs artifacts
  condition: succeededOrFailed()

- task: CopyFiles@1
  inputs:
    Contents: |
      bin/*.unitypackage
    TargetFolder: $(Build.ArtifactStagingDirectory)/deployables
    flattenFolders: true
  displayName: Collecting deployables
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/deployables
    ArtifactName: deployables
    ArtifactType: Container
  displayName: Publish deployables artifacts
  condition: succeededOrFailed()
