parameters:
- name: windowsPool
  type: object
  default:
    vmImage: windows-2022
- name: includeMacOS

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud -c'
    displayName: Set build number

  - template: dotnet.yml
  - template: expand-template.yml

- job: Linux
  pool:
    vmImage: Ubuntu 20.04
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
  - template: dotnet.yml
  - template: expand-template.yml

- job: macOS
  condition: ${{ parameters.includeMacOS }}
  pool:
    vmImage: macOS-10.15
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
  - template: dotnet.yml
  - template: expand-template.yml

- job: WrapUp
  dependsOn:
  - Windows
  - Linux
  - macOS
  pool:
    vmImage: Ubuntu 20.04
  condition: succeededOrFailed()
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-codecoverage.yml
    parameters:
      includeMacOS: ${{ parameters.includeMacOS }}
  - template: publish-deployables.yml
