steps:
- task: DotNetCoreCLI@2
  displayName: Build MessagePack.sln
  inputs:
    command: build
    arguments: --no-restore /p:platform=NoVSIX -c $(BuildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    projects: tests/MessagePack.Tests/MessagePack.Tests.csproj
    arguments: --no-build -c $(BuildConfiguration) -f netcoreapp2.1 -v n
