parameters:
  initArgs:

steps:

- powershell: |
    .\init.ps1 ${{ parameters['initArgs'] }} -UpgradePrerequisites
    dotnet --info
  displayName: Install prerequisites

- powershell: azure-pipelines/variables/_pipelines.ps1
  failOnStderr: true
  displayName: Set pipeline variables based on source
